2019-03-30 20:50:00,725 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 09:44:38,541 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 09:44:59,554 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:08:26,031 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:38:22,310 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:47:28,550 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:49:55,884 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:52:11,164 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:52:19,961 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:52:34,320 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:54:25,146 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:54:47,039 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 10:55:36,386 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:02:20,340 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:07:56,976 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:13:51,753 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:19:15,240 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:19:57,701 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:20:17,564 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:20:25,370 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:20:28,765 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:20:30,019 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:20:31,847 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:21:13,092 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:21:14,620 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:21:28,626 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:21:29,838 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:21:30,704 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:21:31,385 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:22:17,739 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:22:19,223 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:22:20,058 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:23:23,599 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:31:47,423 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
2019-03-31 11:32:41,260 ERROR: Exception on /user/aaajjj1625 [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/workspace/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/python/workspace/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}
  File "/home/python/workspace/microblog/app/templates/user.html", line 14, in block "content"
    {% elif not current_user.is_following(user) %}
UndefinedError: 'app.models.User object' has no attribute 'is_following'
2019-03-31 11:32:48,097 ERROR: Exception on /user/aaajjj1625 [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/workspace/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/python/workspace/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}
  File "/home/python/workspace/microblog/app/templates/user.html", line 14, in block "content"
    {% elif not current_user.is_following(user) %}
UndefinedError: 'app.models.User object' has no attribute 'is_following'
